sudo: required # sudo will add the super user permission for traviCI for using docker

services: 
    - docker

before_install:
    - docker build -t kvmukesh/reactjs-webapp -f Dockerfile.dev .

script:
    - docker run -e CI=true kvmukesh/reactjs-webapp npm run test