version: '3'

services:
    reactjs-webapp:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
    tests:
        image: react-webapp_reactjs-webapp:latest
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]